### ISSUE TITLE
Aquarius modal

### ISSUE THREAD

**Issue by kvothe1387** [kvothe1387/Horoscope-Dreems#11]
Aquarius card modal including sign with least compatibility, most likely way to die, 1-3 negative traits, and top challenge

**Comment by jesseunderwood** [comment]
As an Aquarius, the least compatible zodiac sign would be Cancer. The most likely way to die would be trying to prove a point. The top negative trait of an Aquarius would be their stubbornness, and freedom is of the utmost importance for Aquarians, who view challenges to their independence as power-hungry attempts to control them. To win an Aquarian's trust, don't try to reign in their quirks or keep them from flying their freak flag high—Aquarius thrives on shock value.
