### ISSUE TITLE
Capricorn modal

### ISSUE THREAD

**Issue by kvothe1387** [kvothe1387/Horoscope-Dreems#13]
Capricorn card modal including sign with least compatibility, most likely way to die, 1-3 negative traits, and top challenge

**Comment by jesseunderwood** [comment]
As an Capricorn, the least compatible with Aries. The most likely way to die would be to be crushed to death by a dropped bar bell, some negative traits would be is that they can Condescending, critical, and bossy. Top challenges would be workaholism, rigidity, and difficulty letting go.
